version: 2.1
aliases:
  - &defaults
    docker:
      - image: circleci/python:3.7-bullseye

jobs:
  build_test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install dist/convrsn-0.0.2-py3-none-any.whl
            # pipenv install pytest
      # - run:
      #     command: |  # Run test suite
      #       pipenv run pytest
  test_pypi_publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          command: |  # publish to Test PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/*
  pypi_publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          command: |  # publish to real PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
      # - pypi_publish:
      #     requires:
      #       - build_test
      #     filters:
      #       branches:
      #         only:
      #           - main
